#!/bin/sh
#
# @name Hexa X Tilt p
#
# @type Tilt-Hexarotor
# @class Copter
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
#
# @maintainer Li Zhengchen <lizc@hnu.edu.cn>
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	param set MC_PITCHRATE_P 0.1
	param set MC_ROLLRATE_P 0.1
	param set MC_YAWRATE_P 0.08

	param set MC_PITCHRATE_MAX 20.0
	param set MC_ROLLRATE_MAX 20.0
	param set MC_YAWRATE_MAX 60.0


	param set MPC_USE_HTE 1

	param set RTL_DESCEND_ALT 5.0
	param set RTL_LAND_DELAY 5

	param set SDLOG_PROFILE 179

	param set OMNI_ATT_MODE 2
	param set OMNI_DFC_MAX_THR 0.2
fi

set MAV_TYPE 13

# Set mixer
set MIXER hexa_x_tilt
